name: dacsslide_remote
description: Remote Controller for DaCSSLide
version: 0.0.2+2
author: Valentyn Shybanov <olostan@gmail.com>
homepage: https://github.com/olostan/dacsslide_remote

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular: '>=1.0.0 <1.9.0'
  dacsslide: '>=0.0.14 <0.1.0'
  csslib_transform: '>=0.0.0 <0.1.0'
  shelf: '>=0.6.5 <1.0.0'
  shelf_web_socket: '>=0.0.1 <0.1.0'


transformers:
- angular
- dacsslide
- csslib_transform

executables:
  remote_server: